services:
  # ----------------------------------------------------
  # Spring Boot Java Backend Service
  # ----------------------------------------------------
  - type: web
    name: airbnb-clone-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: "*"

  # ----------------------------------------------------
  # Next.js React Frontend Service
  # ----------------------------------------------------
  - type: web
    name: airbnb-clone-frontend
    env: node
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: airbnb-clone-backend
          property: url
      - key: BACKEND_URL
        fromService:
          type: web
          name: airbnb-clone-backend
          property: url
